#!/bin/sh -e

basedir=$(dirname $0)

if [ "$1" = "-q" ]
then
    output=true
    shift 1
else
    output=echo
fi

version=${1:-`$basedir/version`}

if (echo "$version" | grep -Eq '^[0-9]+(\.[0-9]+){2}(-RC[0-9]+)?$')
then
    $output yes
    true
else
    $output no
    false
fi
